package tech.toughput.dicodingsubmissionpemula;

import java.util.ArrayList;

public class FoodData {

    public static String[][] data = new String[][]{
            {"Nasi Goreng", "Literally means fried rice, it is actually the usual famous Southeast Asian style of stir-frying cooked rice, but with it’s very own Indonesian spices and mix", "https://allindonesiatravel.com/images/nasi-goreng-fried-rice-indonesia-must-eat.jpg", "How To Make : Nasi Goreng", "Material :\n\n 3 tablespoons of cooking oil.\n 2 garlic cloves, sprinkled\n 2 red chilies\n 1 egg\n 100 grams of peas\n 1 carrot, diced and then boiled\n 100 grams of minced chicken\n 500 grams of white rice\n 1 stalk of leeks\n 1 tablespoon of soy sauce\n 1 teaspoon of powdered pepper\n\n How to make :\n\n Heat oil, saute garlic and red chili until fragrant. Add the eggs, stir until smooth.\n Add peas, carrots, chicken and chives, stir until smooth.\n Add rice, give soy sauce and pepper powder, stir until smooth.\n Serve it.", "https://id.wikibooks.org/wiki/Resep:Nasi_Goreng_Ayam"},
            {"Rendang", "Literally means dry curry, rendang is a really popular dish in Indonesia that is actually a dry beef stew.", "https://norecipes.com/wp-content/uploads/2012/01/recipebeef-rendang-recipe.1024x1024.jpg", "How To Make : Rendang", "Material :\n\n 1 kg of beef or buffalo, cut square into about 20 pieces, eat beef.\n 4 orange leaves\n 1 lemongrass stem\n 2 liters of thick coconut milk from 1 large old coconut\n\n Softened seasoning :\n\n 2 cloves of garlic\n 4 shallots\n 25 grams of ginger\n 15 grams of turmeric\n 75 grams of young galangal\n 1 tbsp. ground chili or according to taste\n 1 tsp. pepper\n½ nutmeg\n 4 candlenuts\n½ tbsp. salt\n 1 tbsp. sugar\n\n How to make :\n\n Soak the meat with mashed spices for at least 1 hour\n Cook the coconut milk over the pan over medium heat, stirring once in a while until the oil from the coconut milk floats on the surface (at least 20 minutes) and set aside\n In a large skillet, add the meat with seasonings and coconut milk as much as 300 cc (until the meat is submerged)\n Add bay leaves and lemongrass leaves, cook over medium heat while stirring until half of the coconut milk evaporates\n Pour 100 cc of coconut milk and stir until all the water in the coconut milk evaporates \n Continue stirring and adding the remaining coconut milk, about 100 cc for one pour. \n Cook until the meat becomes tender (at least 1½ hours) and until all the water in the coconut milk evaporates and the rendang seasoning is finished.", "https://id.wikibooks.org/wiki/Resep:Rendang"},
            {"Gudeg", " A traditional food hail from Yogyakarta in Central Java, gudeg is a stew made from young jack fruit (nangka) with palm sugar, coconut milk, meat, garlic, and lots of spices.", "https://allindonesiatravel.com/images/wijilan-gudeg-yogayakarta-indonesia-must-eat.jpg", "How To Make : Gudeg", "Material :\n\n 1 kg of young jackfruit, cut into small pieces\n 2 bay leaves\n 1 scalloped galangal, bruised\n\n Softened seasoning :\n\n 10 shallots\n 3 garlic cloves\n 1/2 teaspoon coriander\n 4 pecan nuts\n 250 grams of brown sugar\n Salt\n\n How to make :\n\n Boil in a cauldron, jackfruit with fine spices and enough water until the jackfruit is soft and has a red color, remove it\n Let stand 1 night in a cauldron\n Serve with poured areh on top.", "https://id.wikibooks.org/wiki/Resep:Gudeg_Yogya"},
            {"Soto Betawi", "There are a few Soto here in Indonesia that you must try, first is the Soto Betawi.", "https://allindonesiatravel.com/images/soto-betawi-indonesia-must-eat.jpg", "How To Make : Soto Betawi", "Material :\n\n 500g jerohan (intestine, lung and tripe)\n 500g beef stirring (upper thigh)\n 2 potatoes, peeled, divided into 4 parts, and fried\n 2 sticks of lemongrass, crushed\n 3 bay leaves\n 3 orange leaves\n 1½ liters of thick coconut milk\n 2 tablespoons of lemon juice\n 2 tablespoons fried onions\n 1 stem sliced finely onion\n 1 tomato is cut into 8 parts\n 1 tablespoon of celery leaves finely chopped\n 1 cinnamon stick\n 1 teaspoon salt\n 1 tablespoon sugar\n oil for sautéing\n fried crackers melinjo\n\n Softened seasoning :\n\n 3 garlic cloves\n 7 shallots\n 3 pecan nuts\n 2 teaspoons of cumin\n 2 teaspoons of pepper\n 3 teaspoons of coriander\n\n How to make :\n\n Clean the jerohan, then boil it to uk tender. Lift and set aside.\n Boil the coconut milk to a boil over low heat. Enter offal and meat. Boil again until both are cooked.\n Saute the mashed spices until they are fragrant and cooked. Add lemongrass, bay leaves, orange leaves and cinnamon. After the spices are really fragrant and cooked, put the innards, meat, salt, and sugar into the stew.\n Lift offal and meat. Cut to taste, then fry. Set it aside.\n\n How To Serve : \n\n Place pieces of fried potatoes, pieces of offal and meat, leeks, celery leaves, and lime juice at the base of the bowl.\n Flush with soup soup. Finally, sprinkle with fried onions. Serve with crackers melinjo.", "https://id.wikibooks.org/wiki/Resep:Soto_Betawi"},
            {"Ketoprak", "Ketoprak is one of Indonesian traditional food. It is a mix of bean-sprout, deep-fried tofu, onion, eggs with special peanut sauce.", "https://upload.wikimedia.org/wikipedia/commons/2/2e/Ketoprak_Boplo.JPG", "How To Make : Ketoprak", "Material :\n\n 150 grams of vermicelli, boil hot water, drain\n 150 grams of sprouts, boil hot water, drain\n 4 white tofu, fried, cut into cubes\n 4 rice cake, cut 1 cm round\n\n Sauce : \n\n 3 garlic cloves\n 5 cayenne fruit\n 2 red chilies\n 50 grams of peanuts, roasted\n 2 tablespoons of acidic water\n 100 cc of hot water\n 1 teaspoon of salt\n 2 tablespoons of sweet soy sauce\n\n Complementary : \n\n 100 grams of fried chips\n 1 tablespoon of fried shallots\n\n How To Make : \n\nSauce : Blend the garlic, cayenne pepper, red chili, peanuts, and salt, then add sour water, hot water, and sweet soy sauce, mix well, set aside.\n Place the rice cake, vermicelli, bean sprouts, and white tofu over the serving dish, pour the sauce on top, then sprinkle with fried chips and fried shallots on top, serve.", "https://id.wikibooks.org/wiki/Resep:Ketoprak"},
            {"Rawon", "Rawon is a black beef soup, made with beef and keluak (black nuts) as the main spice giving it a strong nutty taste and dark in colour, along with other spices and normally served with rice.", "https://scm-assets.constant.co/scm/unilever/1db348501df1238f872479d225e08c34/69eda29e-7e2a-4747-8d03-e7d3035fac9d.jpg", "How To Make : Rawon", "Material :\n\n 600 grams of beef\n 2 liters of water\n 2 bay leaves\n 3 sticks of lemongrass, bruised\n 3 cm galangal, bruised\n 5 orange leaves\n 3 tablespoons of oil to saute\n\n Softened seasoning :\n\n 5 shallots\n 3 garlic cloves\n 4 red chilies\n 2 pecan nuts\n 1 teaspoon of coriander\n 4 steamed old fruits\n 2 cm of ginger\n 2 cm turmeric\n 1 teaspoon of shrimp paste cooked\n 2 teaspoons of salt\n 2 chives, cut into pieces\n 100 grams of short bean sprouts\n 2 salted eggs\n\n How To Make : \n\n Cook the meat with bay leaves, lemongrass, galangal, and orange leaves until tender and cooked. Lift the meat, then cut into small pieces. Strain the stew, boil it again with the sliced meat.\n Heat oil, sauté fine spices with sliced leeks until fragrant and cooked. Remove, then put in the meat broth. Cook over low heat until boiling again.\n Pour the rawon into a bowl, sprinkle the short bean sprouts on top. Serve with salted eggs and shrimp paste and chips.", "https://id.wikibooks.org/wiki/Resep:Rawon"},
            {"Sayur Asem", "Sayur Asem or sayur asam (literally sour vegetables) is a tamarind soup made from peanuts, young jackfruit, melinjo, long beans, chayote, corn and meat stock (normally beef) and of course tamarind.", "https://www.primarasa.co.id/images/images/Sayur%20Asem%20-%20Resep%282%29.jpg", "How To Make : Sayur Asem", "Material :\n\n 75 grams of beans, cut 2 cm in length\n 75 grams of squash, diced\n 1 corn, cut into 2 round parts\n 50 grams of peanut peels, wash thoroughly\n 75 grams of melinjo\n 50 grams of melinjo leaves\n 75 grams of young jackfruit, cut into the same shape\n 3 red chili\n 3 cm galangal, bruised\n 3 bay leaves\n 75 gr young tamarind\n 1000 ml of water\n 5 tablespoons of sugar\n 3 teaspoons of salt\n 25 grams of tamarind\n 1000 ml of hot water\n\n Softened seasoning :\n\n 7 shallots\n 3 garlic cloves\n 3 red chilies\n 50 grams of peanuts\n\n How To Make :\n\n Boil water with galangal, bay leaves, young tamarind, salt, sugar, and spices that have been mashed to a boil.\n Add all ingredients, cook until sufficiently mature.\n Add the last 2 ingredients (only water), cook until cooked. Lift and tamarind vegetables ready to be served.", "https://id.wikibooks.org/wiki/Resep:Rawon", "https://id.wikibooks.org/wiki/Resep:Sayur_asem"}
    };

    public static ArrayList<Food> getListData(){
        ArrayList<Food> list = new ArrayList<>();
        for (String[] fData : data) {
            Food food = new Food();
            food.setName(fData[0]);
            food.setRemarks(fData[1]);
            food.setPhoto(fData[2]);
            food.setJudul(fData[3]);
            food.setRecipe(fData[4]);
            food.setLink(fData[5]);
            list.add(food);
        }
        return list;
    }
}
